export const a = Promise.reject("kaboom");
                 ~~~~~~~~~~~~~~~~~~~~~~~~                                                   [throw-error]
export const b = Promise.reject(new Error("kaboom"));
export const c = new Promise((resolve, reject) => reject("kaboom"));
                                                  ~~~~~~~~~~~~~~~~                          [throw-error]
export const d = new Promise((resolve, reject) => reject(new Error("kaboom")));
export const e = new Promise(function (resolve, reject) { reject("kaboom"); });
                                                          ~~~~~~~~~~~~~~~~                  [throw-error]
export const f = new Promise(function (resolve, reject) { reject(new Error("kaboom")); });

const kaboom: any = new Error("kaboom");
export const g = Promise.reject(kaboom);
export const h = new Promise(function (resolve, reject) { reject(kaboom); });

export const i = Promise.reject(new DOMException("boom"));
export const j = new Promise(function (resolve, reject) { reject(new DOMException("boom")); });

[throw-error]: Throwing non-Error values is forbidden
